version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          PGUSER: root
      - image: circleci/postgres:10.5-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: laa-great-ideas_test

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: npm
          command: npm install
      - run:
          name: bundle
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: Crate Database
          command: bundle exec rake db:create db:schema:load
